# Aqara Switch Matter Blueprint
# Version: 1.1.0
# Changelog:
#   1.1.0 - Restructured repository, added configurable automation mode
#   1.0.0 - Initial release

blueprint:
  name: Aqara Switch Actions with Matter
  description: |
    Handle different actions for an Aqara switch button using Matter protocol.

    **Supported events:** Single press, Double press, Long press, Long release

    **Note:** Automatically filters out unavailable/unknown state transitions to prevent false triggers during hub reconnections.
  domain: automation
  author: Jean-Michel Audet
  source_url: https://github.com/jeanmichelaudet/ha-blueprints/blob/main/blueprints/automation/jeanmichelaudet/aqara-switch-matter.yaml
  homeassistant:
    min_version: "2022.5.0"
  input:
    switch_section:
      name: Device
      icon: mdi:light-switch
      description: Select the Aqara switch to monitor
      collapsed: false
      input:
        switch_entity:
          name: Switch Entity
          description: The Aqara switch button entity (event domain)
          selector:
            entity:
              filter:
                domain: event
                device_class: button
    actions_section:
      name: Actions
      icon: mdi:gesture-tap
      description: Configure at least one action
      collapsed: false
      input:
        single_press_action:
          name: Single Press
          description: Action on single press (multi_press_1)
          default: []
          selector:
            action: {}
        double_press_action:
          name: Double Press
          description: Action on double press (multi_press_2)
          default: []
          selector:
            action: {}
        long_press_action:
          name: Long Press
          description: Action when button is held (long_press)
          default: []
          selector:
            action: {}
        long_release_action:
          name: Long Release
          description: Action when button is released after hold (long_release)
          default: []
          selector:
            action: {}
    options_section:
      name: Options
      icon: mdi:cog
      description: Advanced configuration options
      collapsed: true
      input:
        automation_mode:
          name: Automation Mode
          description: |
            How to handle multiple triggers:
            - **single**: Ignore new triggers while running
            - **restart**: Restart automation on new trigger
            - **queued**: Queue triggers and run sequentially
            - **parallel**: Run multiple instances simultaneously
          default: single
          selector:
            select:
              options:
                - label: Single (ignore new triggers)
                  value: single
                - label: Restart (cancel and restart)
                  value: restart
                - label: Queued (run sequentially)
                  value: queued
                - label: Parallel (run simultaneously)
                  value: parallel

variables:
  event_type: "{{ trigger.to_state.attributes.event_type }}"
  valid_events:
    - multi_press_1
    - multi_press_2
    - long_press
    - long_release

trigger:
  - platform: state
    entity_id: !input switch_entity
    not_from:
      - "unavailable"
      - "unknown"
    not_to:
      - "unavailable"
      - "unknown"

condition:
  - condition: template
    value_template: "{{ event_type in valid_events }}"

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ event_type == 'multi_press_1' }}"
        sequence: !input single_press_action
      - conditions:
          - condition: template
            value_template: "{{ event_type == 'multi_press_2' }}"
        sequence: !input double_press_action
      - conditions:
          - condition: template
            value_template: "{{ event_type == 'long_press' }}"
        sequence: !input long_press_action
      - conditions:
          - condition: template
            value_template: "{{ event_type == 'long_release' }}"
        sequence: !input long_release_action

mode: !input automation_mode
max_exceeded: silent
